name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk-headless autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          # Создаем папку для лицензий
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Устанавливаем SDK-manager и принимаем лицензии официально
          export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          
          # Запускаем сборку
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
