name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk-headless autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Prepare Buildozer
        run: |
          # Запускаем подготовку, которая скачает SDK
          # Мы используем 'yes |' чтобы он сам прожал все лицензии при установке
          yes | buildozer android debug || true

      - name: Build APK
        run: |
          # Теперь, когда SDK скачан и лицензии приняты, запускаем основную сборку
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
